Metrics/LineLength:
  Max: 96

Metrics/ClassLength:
  Max: 153

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 20
